### ISSUE TITLE
getbalance throws error after first asset from coinprism arrives in the wallet

### ISSUE THREAD

**Issue by ganeshjung** [OpenAssets/colorcore#10]
Hi,

I've set up my local testnet bitcoind and connected colorcore to it. Ive use these parameters for the bitcoin testnet:
version-byte=111
p2sh-version-byte=196
asset-version-byte=115

I was able send Bitcoins to the testnet wallet and
python colorcore.py getbalance
would give me a JSON object with the correct answer.

Now I've created an asset https://testnet.coinprism.info/asset/oZrgafn6vCZjdMb37zNVgcnjkpcnD1yPM5 
on testnet.coinprism.com.
I've sent some of these colored coins to my colorcore wallet with this transaction:
https://testnet.coinprism.info/tx/e4ab8f5128f2c3758da34f823fdf714139ebe26cb11c9ca4924bf05b912a8061

I can see in bitcoin-qt that the transfer is confirmed, but now
python colorcore.py getbalance
gives me an exception. Can you please give me an idea why this doesn't work? It's on the testnet, so I can also provide the private key, if required.

Here's the stack trace:

C:\Users\ganesh\Documents\Projekte\Bitcoin\coloredcoins\colorcore>c:\Python34\python  colorcore.py getbalance
Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\bitcoin\rpc.py", line 307, in getrawtransaction
    r = self._call('getrawtransaction', b2lx(txid), 1 if verbose else 0)
  File "c:\Python34\lib\site-packages\bitcoin\rpc.py", line 146, in _call
    raise JSONRPCException(response['error'])
bitcoin.rpc.JSONRPCException: msg: 'No information available about transaction'  code: -5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "colorcore.py", line 35, in <module>
    colorcore.routing.Program.execute()
  File "C:\Users\ganesh\Documents\Projekte\Bitcoin\coloredcoins\colorcore\colorcore\routing.py", line 64, in execute
    router.parse(sys.argv[1:])
  File "C:\Users\ganesh\Documents\Projekte\Bitcoin\coloredcoins\colorcore\colorcore\routing.py", line 338, in parse
    func(*_args)
  File "C:\Users\ganesh\Documents\Projekte\Bitcoin\coloredcoins\colorcore\colorcore\routing.py", line 255, in decorator
    self.event_loop.run_until_complete(coroutine_wrapper())
  File "c:\Python34\lib\asyncio\base_events.py", line 316, in run_until_complete
    return future.result()
  File "c:\Python34\lib\asyncio\futures.py", line 275, in result
    raise self._exception
  File "c:\Python34\lib\asyncio\tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "C:\Users\ganesh\Documents\Projekte\Bitcoin\coloredcoins\colorcore\colorcore\routing.py", line 240, in coroutine_wrapper
    result = yield from function(controller, *args, *_kwargs)
  File "C:\Users\ganesh\Documents\Projekte\Bitcoin\coloredcoins\colorcore\colorcore\operations.py", line 61, in getbalance
    from_address, min_confirmations=self._as_int(minconf), max_confirmations=self._as_int(maxconf))
  File "C:\Users\ganesh\Documents\Projekte\Bitcoin\coloredcoins\colorcore\colorcore\operations.py", line 343, in _get_unspent_outputs
    output_result = yield from engine.get_output(item['outpoint'].hash, item['outpoint'].n)
  File "c:\Python34\lib\site-packages\openassets\protocol.py", line 73, in get_output
    colored_outputs = yield from self.color_transaction(transaction)
  File "c:\Python34\lib\site-packages\openassets\protocol.py", line 104, in color_transaction
    self.get_output(input.prevout.hash, input.prevout.n), loop=self._loop)))
  File "c:\Python34\lib\asyncio\futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "c:\Python34\lib\asyncio\tasks.py", line 287, in _wakeup
    value = future.result()
  File "c:\Python34\lib\asyncio\futures.py", line 275, in result
    raise self._exception
  File "c:\Python34\lib\asyncio\tasks.py", line 238, in _step
    result = next(coro)
  File "c:\Python34\lib\site-packages\openassets\protocol.py", line 68, in get_output
    transaction = yield from self._transaction_provider(transaction_hash)
  File "c:\Python34\lib\asyncio\coroutines.py", line 141, in coro
    res = func(_args, *_kw)
  File "C:\Users\ganesh\Documents\Projekte\Bitcoin\coloredcoins\colorcore\colorcore\providers.py", line 91, in get_transaction
    return self._proxy.getrawtransaction(transaction_hash)
  File "c:\Python34\lib\site-packages\bitcoin\rpc.py", line 310, in getrawtransaction
    (self.__class__.**name**, ex.error['message'], ex.error['code']))
IndexError: Proxy.getrawtransaction(): No information available about transaction (-5)

Any help is highly appreciated.

Regards,
Ganesh

**Comment by Flavien** [comment]
You need to run Bitcoin with the `txindex=1` configuration option. See [this answer](http://bitcoin.stackexchange.com/a/9152/2716) for more details.

**Comment by ganeshjung** [comment]
Yes, this helps. Thank you for this cool software.
