### ISSUE TITLE
Getbalance error?

### ISSUE THREAD

**Issue by off-bank** [OpenAssets/colorcore#16]
While bitcoin core was updating, I sent an asset amount, and getbalance was returning "[]".
After bitcoin core in sync, I get the following error. Why is that?

root@node:/usr/share/colorcore# python3.5 colorcore.py getbalance
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/bitcoin/rpc.py", line 307, in getrawtransaction
    r = self._call('getrawtransaction', b2lx(txid), 1 if verbose else 0)
  File "/usr/local/lib/python3.5/site-packages/bitcoin/rpc.py", line 146, in _call
    raise JSONRPCException(response['error'])
bitcoin.rpc.JSONRPCException: msg: 'No information available about transaction'  code: -5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "colorcore.py", line 35, in <module>
    colorcore.routing.Program.execute()
  File "/usr/share/colorcore/colorcore/routing.py", line 64, in execute
    router.parse(sys.argv[1:])
  File "/usr/share/colorcore/colorcore/routing.py", line 338, in parse
    func(*_args)
  File "/usr/share/colorcore/colorcore/routing.py", line 255, in decorator
    self.event_loop.run_until_complete(coroutine_wrapper())
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/share/colorcore/colorcore/routing.py", line 240, in coroutine_wrapper
    result = yield from function(controller, *args, *_kwargs)
  File "/usr/share/colorcore/colorcore/operations.py", line 61, in getbalance
    from_address, min_confirmations=self._as_int(minconf), max_confirmations=self._as_int(maxconf))
  File "/usr/share/colorcore/colorcore/operations.py", line 343, in _get_unspent_outputs
    output_result = yield from engine.get_output(item['outpoint'].hash, item['outpoint'].n)
  File "/usr/local/lib/python3.5/site-packages/openassets/protocol.py", line 73, in get_output
    colored_outputs = yield from self.color_transaction(transaction)
  File "/usr/local/lib/python3.5/site-packages/openassets/protocol.py", line 104, in color_transaction
    self.get_output(input.prevout.hash, input.prevout.n), loop=self._loop)))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/site-packages/openassets/protocol.py", line 73, in get_output
    colored_outputs = yield from self.color_transaction(transaction)
  File "/usr/local/lib/python3.5/site-packages/openassets/protocol.py", line 104, in color_transaction
    self.get_output(input.prevout.hash, input.prevout.n), loop=self._loop)))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/site-packages/openassets/protocol.py", line 73, in get_output
    colored_outputs = yield from self.color_transaction(transaction)
  File "/usr/local/lib/python3.5/site-packages/openassets/protocol.py", line 104, in color_transaction
    self.get_output(input.prevout.hash, input.prevout.n), loop=self._loop)))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/site-packages/openassets/protocol.py", line 73, in get_output
    colored_outputs = yield from self.color_transaction(transaction)
  File "/usr/local/lib/python3.5/site-packages/openassets/protocol.py", line 104, in color_transaction
    self.get_output(input.prevout.hash, input.prevout.n), loop=self._loop)))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/site-packages/openassets/protocol.py", line 68, in get_output
    transaction = yield from self._transaction_provider(transaction_hash)
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 206, in coro
    res = func(_args, *_kw)
  File "/usr/share/colorcore/colorcore/providers.py", line 91, in get_transaction
    return self._proxy.getrawtransaction(transaction_hash)
  File "/usr/local/lib/python3.5/site-packages/bitcoin/rpc.py", line 310, in getrawtransaction
    (self.__class__.**name**, ex.error['message'], ex.error['code']))
IndexError: Proxy.getrawtransaction(): No information available about transaction (-5)
root@node:/usr/share/colorcore#

**Comment by off-bank** [comment]
txindex=1
