### ISSUE TITLE
Exploring transactions for particular asset

### ISSUE THREAD

**Issue by mastercyb** [OpenAssets/colorcore#3]
It would be great if i'll have possibility to explore transactions only with my asset. Analog of block explorer, but only for one asset. There is quantity of transactions in coinprism explorer, but there is now possibility to look for these transactions.

**Comment by footmanyjp** [comment]
when i run " python3 colorcore.py issueasset  1BL7j6wzma49rs7AGvvHsvh94guansGTwg  1000"
errors like this :
Traceback (most recent call last):
  File "colorcore.py", line 35, in <module>
    colorcore.routing.Program.execute()
  File "/root/colorcore/colorcore/routing.py", line 64, in execute
    router.parse(sys.argv[1:])
  File "/root/colorcore/colorcore/routing.py", line 338, in parse
    func(*_args)
  File "/root/colorcore/colorcore/routing.py", line 255, in decorator
    self.event_loop.run_until_complete(coroutine_wrapper())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 302, in _step
    result = next(coro)
  File "/root/colorcore/colorcore/routing.py", line 240, in coroutine_wrapper
    result = yield from function(controller, *args, *_kwargs)
  File "/root/colorcore/colorcore/operations.py", line 195, in issueasset
    to_address = self._as_any_address(from_address)
  File "/root/colorcore/colorcore/operations.py", line 287, in _as_any_address
    result = colorcore.addresses.Base58Address.from_string(address)
  File "/root/colorcore/colorcore/addresses.py", line 67, in from_string
    decoded_bytes = bitcoin.base58.decode(base58)
  File "/usr/local/lib/python3.4/dist-packages/python_bitcoinlib-0.2.2_SNAPSHOT-py3.4.egg/bitcoin/base58.py", line 75, in decode
    if c not in b58_digits:
TypeError: 'in <string>' requires string as left operand, not int

**Comment by Flavien** [comment]
@footmanyjp This has been resolved in [this commit](https://github.com/OpenAssets/colorcore/commit/55bdad2f83479ef6bc5404ff6e8b0f0d20a3727f).

@21xhipster Ok, this is a feature request for Coinprism. I am tracking this separately and closing this issue as this is issue tracking for Colorcore.
