### ISSUE TITLE
this is what i get when asking for help

### ISSUE THREAD

**Issue by chrisfranko** [OpenAssets/colorcore#4]
root@franko:~/colorcore# python colorcore.py --help
Traceback (most recent call last):
  File "colorcore.py", line 31, in <module>
    import colorcore.routing
  File "/root/colorcore/colorcore/routing.py", line 126
    return (yield from self.error(102, 'The request path is invalid', message))
                     ^

**Comment by chrisfranko** [comment]
Seems I get this error no matter what I do.

python colorcore.py getbalance

Traceback (most recent call last):
  File "colorcore.py", line 31, in <module>
    import colorcore.routing
  File "/root/colorcore/colorcore/routing.py", line 126
    return (yield from self.error(102, 'The request path is invalid', message))
                     ^
SyntaxError: invalid syntax

**Comment by Flavien** [comment]
Sorry for the late reply. This sounds like you are using a python interpreter older than 3.4. Can you try to follow these steps to make sure you are using the 3.4 interpreter and see if it helps: https://github.com/OpenAssets/colorcore/issues/1#issuecomment-57279006

**Comment by chrisfranko** [comment]
happy@happiness:~$ sudo apt-get install python3.4
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3.4 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 152 not upgraded.
happy@happiness:~$ sudo python3.4 -m ensurepip
/usr/bin/python3.4: No module named ensurepip
happy@happiness:~$ sudo pip3.4 install --upgrade setuptools
sudo: pip3.4: command not found
happy@happiness:~$ sudo pip3.4 install --upgrade -r requirements.txt
sudo: pip3.4: command not found

**Comment by donpdonp** [comment]
If you need pip for python on ubuntu, run
$ sudo apt-get install python-pip

after that, running pip directly should work, no need to say pip3.4.

**Comment by chrisfranko** [comment]
donp yea that's what i originally did haha and i kept getting that weird error.

**Comment by hughmadden** [comment]
pretty late response but on ubuntu you want something like:
apt-get install python3.4
apt-get install python3-pip
pip3 install openassets==1.3
pip3 install python-bitcoinlib==0.2.1
pip3 install aiohttp==0.9.2

then when you run colorcore:
python3.4 colorcore.py -h

**Comment by chrisfranko** [comment]
you are a god
